# Site settings
title: LambdaVPS
email: zmccorkle@lambdavps.xyz
description: > # this means to ignore newlines until "baseurl:"
  Cheap VPS Hosting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lambdavps.xyz" # the base hostname & protocol for your site
twitter_username: LambdaVPS
github_username:  LambdaVPS
control-panel: https://lambdavps.myvirtkick.com/

# Build settings
markdown: kramdown
